package br.nnpe.cligen.internal;

import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

import br.nnpe.cligen.BarraSetTop;
import br.nnpe.cligen.ExcelAdapter;
import br.nnpe.cligen.MainFrame;
import br.nnpe.cligen.table.CachingResultSetTableModel;
import br.nnpe.cligen.table.ResultSetTableModel;

/**
 * 
 * @author Sobreira Created on 16 de Janeiro de 2003, 13:33
 */
public class PesquisaInternalFrame extends javax.swing.JInternalFrame {
	private static int numJanela;

	private Statement stmt;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton atualiza;
	private javax.swing.JScrollPane jScrollPaneResultadoPesquisa;
	private javax.swing.JPanel botoesSQLPanel;
	private javax.swing.JButton consulta;
	private javax.swing.JPanel jPanelConsulta;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextAreaConsulta;
	private javax.swing.JTextArea jTextAreaCampos;
	private javax.swing.JPanel jPanelResultado;
	private javax.swing.JTable jTableResultado;
	private String tbName;

	public PesquisaInternalFrame(ResultSetTableModel amodel, String aTBname, Statement astmt) {
		super();
		this.tbName = aTBname;
		numJanela++;
		initComponents();
		this.setTitle(aTBname);

		if (amodel != null) {
			jTableResultado.setModel(amodel);
			initColumnSizes(jTableResultado);
		}
		stmt = astmt;
		setVisible(true);
		pack();
		try {
			setSelected(true);
		} catch (PropertyVetoException e) {
			e.printStackTrace();
		}
	}

	public String getTitle() {
		return super.getTitle() + " " + numJanela;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() { // GEN-BEGIN:initComponents
		jPanelResultado = new javax.swing.JPanel();
		jScrollPaneResultadoPesquisa = new javax.swing.JScrollPane();
		jTableResultado = new javax.swing.JTable();
		jPanelConsulta = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextAreaConsulta = new javax.swing.JTextArea();
		botoesSQLPanel = new javax.swing.JPanel();
		consulta = new javax.swing.JButton();
		atualiza = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setMaximizable(true);
		setResizable(true);
		jPanelResultado.setLayout(new java.awt.BorderLayout());
		new ExcelAdapter(jTableResultado);
		jTableResultado.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {}, new String[] {}));
		jScrollPaneResultadoPesquisa.setViewportView(jTableResultado);
		jTableResultado.setAutoCreateRowSorter(true);

		jTableResultado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		jTableResultado.getModel().addTableModelListener(new TableModelListener() {

			public void tableChanged(TableModelEvent e) {
				initColumnSizes(jTableResultado);
			}
		});

		jPanelConsulta.setLayout(new java.awt.BorderLayout());

		jTextAreaConsulta.setRows(5);
		jTextAreaConsulta.setBackground(MainFrame.bgColor);
		jScrollPane2.setViewportView(jTextAreaConsulta);

		jTextAreaCampos = new JTextArea(25, 18);
		jTextAreaCampos.setBackground(MainFrame.bgColor);

		JSplitPane splitPaneSup = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, jScrollPane2,
				new JScrollPane(jTextAreaCampos));
		jTextAreaCampos.setFont(new Font("Arial", Font.BOLD, 16));
		jTextAreaConsulta.setFont(new Font("Arial", Font.BOLD, 16));
		splitPaneSup.setContinuousLayout(true);
		splitPaneSup.setOneTouchExpandable(true);
		splitPaneSup.setDividerLocation(800);
		jPanelConsulta.add(splitPaneSup, java.awt.BorderLayout.CENTER);
		botoesSQLPanel.setLayout(new java.awt.GridLayout(1, 0));

		consulta.setText("Consulta F5");
		consulta.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				executarConsulta();
			}
		});

		botoesSQLPanel.add(consulta);

		atualiza.setText("Atualização");
		atualiza.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				atualizacao();
			}
		});

		botoesSQLPanel.add(atualiza);

		jPanelConsulta.add(botoesSQLPanel, java.awt.BorderLayout.SOUTH);

		JSplitPane splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, jPanelConsulta, jScrollPaneResultadoPesquisa);
		splitPane.setContinuousLayout(true);
		splitPane.setOneTouchExpandable(true);
		splitPane.setDividerLocation(300);
		jPanelResultado.add(splitPane);
		getContentPane().add(jPanelResultado);
		jTextAreaConsulta.addKeyListener(new KeyAdapter() {
			public void keyPressed(KeyEvent e) {
				int keyCoode = e.getKeyCode();

				if (keyCoode == KeyEvent.VK_F5) {
					executarConsulta();
				}
			}
		});
		addInternalFrameListener(new InternalFrameAdapter() {
			public void internalFrameClosing(InternalFrameEvent e) {
				super.internalFrameClosing(e);
				BarraSetTop.removerJIntenalFrame(PesquisaInternalFrame.this);
			}
		});
		insereBotoesTemplates();
	} // GEN-END:initComponents

	private void adicionarTemplate(String string) {
		jTextAreaConsulta.setText(string + "\n" + jTextAreaConsulta.getText());

	}

	private void initColumnSizes(JTable table) {

		ResultSetTableModel model = (ResultSetTableModel) table.getModel();
		TableColumn column = null;
		Component comp = null;
		int headerWidth = 0;
		TableCellRenderer headerRenderer = table.getTableHeader().getDefaultRenderer();

		for (int i = 0; i < model.getColumnCount(); i++) {
			column = table.getColumnModel().getColumn(i);

			comp = headerRenderer.getTableCellRendererComponent(null, column.getHeaderValue(), false, false, 0, 0);
			headerWidth = comp.getPreferredSize().width + 50;
			column.setMinWidth(headerWidth);
		}
	}

	private void insereBotoesTemplates() {
		JButton select = new JButton("<Select>");
		select.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				adicionarTemplate("select * from " + tbName + ";");

			}

		});
		JButton insert = new JButton("<Insert>");
		insert.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				StringBuffer buffer = new StringBuffer();
				if (jTableResultado.getModel() instanceof ResultSetTableModel) {
					ResultSetTableModel model = (ResultSetTableModel) jTableResultado.getModel();

					buffer.append("(");
					for (int i = 1; i < model.getColumnCount(); i++) {
						buffer.append(model.getColumnName(i));
						if (i == model.getColumnCount() - 1) {
							buffer.append(")");
						} else {
							buffer.append(",");
						}
					}
				}
				String result = buffer.toString();
				adicionarTemplate("insert into " + tbName + " " + result + " values " + result + ";");

			}

		});
		JButton update = new JButton("<Update>");
		update.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				StringBuffer buffer = new StringBuffer();
				if (jTableResultado.getModel() instanceof ResultSetTableModel) {
					ResultSetTableModel model = (ResultSetTableModel) jTableResultado.getModel();
					int[] selectsCols = jTableResultado.getSelectedColumns();
					boolean vaiTodas = false;
					if (selectsCols.length == 0) {
						vaiTodas = true;
					}
					for (int i = 1; i < model.getColumnCount(); i++) {
						if (!vaiTodas) {
							boolean continua = true;
							for (int j = 0; j < selectsCols.length; j++) {
								if (selectsCols[j] == i) {
									continua = false;
								}
							}
							if (continua) {
								continue;
							}
						}
						buffer.append(model.getColumnName(i));
						buffer.append(" = ");
						buffer.append(model.getColumnName(i));
						if (i != model.getColumnCount() - 1) {
							buffer.append(",");
						}
					}
				}
				adicionarTemplate("update " + tbName + " set " + buffer.toString() + " where ? ;");

			}

		});
		JButton delete = new JButton("<Delete>");
		delete.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				adicionarTemplate("delete from " + tbName + " where ? ;");

			}

		});

		JButton campos = new JButton("Campos");
		campos.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				StringBuffer buffer = new StringBuffer();
				if (jTableResultado.getModel() instanceof ResultSetTableModel) {
					ResultSetTableModel amodel = (ResultSetTableModel) jTableResultado.getModel();
					if (amodel == null) {
						return;
					}
					for (int i = 1; i < amodel.getColumnCount(); i++) {
						String nomeCampo = amodel.getColumnName(i);
						String tipoCampo = amodel.getColumnType(i);
						if (nomeCampo != null) {
							nomeCampo = nomeCampo.toUpperCase().trim();
						}
						if (tipoCampo != null) {
							tipoCampo = tipoCampo.toLowerCase().trim();
						}
						buffer.append(nomeCampo + " - " + tipoCampo + amodel.isNullable(i) + "\n");

					}
				}
				if ("".equals(buffer.toString())) {
					JTextArea ta = new JTextArea(3, 15);
					ta.setText("Execute uma consulta Antes");
					JOptionPane.showMessageDialog(PesquisaInternalFrame.this, ta, "Sem Campos",
							JOptionPane.INFORMATION_MESSAGE);
				}
				jTextAreaCampos.setText(buffer.toString());

			}

		});

		botoesSQLPanel.add(select);
		botoesSQLPanel.add(insert);
		botoesSQLPanel.add(update);
		botoesSQLPanel.add(delete);
		botoesSQLPanel.add(campos);
		// TODO Auto-generated method stub

	}

	// GEN-LAST:event_jButton3ActionPerformed

	private void atualizacao() { // GEN-FIRST:event_jButton2ActionPerformed

		// Add your handling code here:
		try {
			String query = jTextAreaConsulta.getSelectedText();
			int afetados = 0;
			if ("".equals(query) || (query == null)) {
				throw new Exception("Selecione um DML");
			}
			if (query.indexOf(";") != -1) {
				query = query.replace(";", "");
			}
			afetados = stmt.executeUpdate(query);

			String txt = "Linhas afetadas: " + afetados + " = " + query.trim();
			JOptionPane.showMessageDialog(this, txt, "Atualização Concluida", JOptionPane.INFORMATION_MESSAGE);
		} catch (Exception e) {
			JTextArea ta = new JTextArea(3, 15);
			ta.setText(e.toString());
			JOptionPane.showMessageDialog(this, ta, "Erro SQL", JOptionPane.ERROR_MESSAGE);
		}
	} // GEN-LAST:event_jButton2ActionPerformed

	private void executarConsulta() {
		try {
			String query = jTextAreaConsulta.getSelectedText();

			if ("".equals(query) || (query == null)) {
				throw new Exception("Selecione uma consulta");
			}
			if (query.indexOf(";") != -1) {
				query = query.replace(";", "");
			}

			ResultSet rs = stmt.executeQuery(query);
			jTableResultado.setModel(new CachingResultSetTableModel(rs));
			initColumnSizes(jTableResultado);
		} catch (Exception e) {
			JTextArea ta = new JTextArea(3, 15);
			ta.setText(e.toString());
			JOptionPane.showMessageDialog(this, ta, "Erro SQL", JOptionPane.ERROR_MESSAGE);
		}
	}

	// End of variables declaration//GEN-END:variables
}
