package sowbreira.DB;

import java.io.File;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Iterator;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

import org.jdom.Document;
import org.jdom.Element;
import org.jdom.input.SAXBuilder;

/**
 * 
 * @author Sobreira Created on 15 de Janeiro de 2003, 15:12
 */
public class ConeccoesInternalFrame extends javax.swing.JInternalFrame {
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private static int numJanela;
	private javax.swing.JCheckBox Jdbc2;
	private javax.swing.JComboBox dbDriver;
	private javax.swing.JButton conectar;
	private javax.swing.JButton abrirTabela;
	private javax.swing.JButton executarConsulta;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPasswordField password;
	private javax.swing.JComboBox url;
	private javax.swing.JTextField user;

	// End of variables declaration//GEN-END:variables
	private ResultSet rs;
	private Statement stmt;

	public ConeccoesInternalFrame() {
		numJanela++;
		initComponents();

		try {
			SAXBuilder builder = new SAXBuilder(
					"org.apache.xerces.parsers.SAXParser");
			Document doc = builder.build(new File("databases.xml"));
			Element root = doc.getRootElement();
			List dbs = root.getChildren("db");
			Iterator i = dbs.iterator();

			while (i.hasNext()) {
				Element db = (Element) i.next();
				dbDriver.addItem(db.getChild("dbdriver").getText().trim());
				url.addItem(db.getChild("dburl").getText().trim());
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage(),
					"Erro de SAXParser", JOptionPane.ERROR_MESSAGE);

		}
	}

	public String getTitle() {
		return super.getTitle() + " " + numJanela;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() { // GEN-BEGIN:initComponents
		jPanel1 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		dbDriver = new javax.swing.JComboBox();
		url = new javax.swing.JComboBox();
		user = new javax.swing.JTextField();
		password = new javax.swing.JPasswordField();
		jPanel7 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		conectar = new javax.swing.JButton();
		Jdbc2 = new javax.swing.JCheckBox();
		abrirTabela = new javax.swing.JButton();
		executarConsulta = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		setClosable(true);
		setIconifiable(true);
		setMaximizable(true);
		setResizable(true);
		setTitle("ConDB");
		setMinimumSize(new java.awt.Dimension(600, 300));
		setPreferredSize(new java.awt.Dimension(600, 300));
		jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

		jPanel1.setBorder(new javax.swing.border.TitledBorder(
				"Conectar ao Banco de Dados"));
		jPanel1.setPreferredSize(new java.awt.Dimension(380, 270));
		jPanel6.setLayout(new java.awt.BorderLayout(10, 10));

		jPanel3.setLayout(new java.awt.GridLayout(4, 0, 5, 5));

		jLabel7.setText("Driver");
		jPanel3.add(jLabel7);

		jLabel8.setText("Url");
		jPanel3.add(jLabel8);

		jLabel9.setText("User");
		jPanel3.add(jLabel9);

		jLabel10.setText("Password");
		jPanel3.add(jLabel10);

		jPanel6.add(jPanel3, java.awt.BorderLayout.WEST);

		jPanel2.setLayout(new java.awt.GridLayout(4, 0, 5, 5));

		dbDriver.setEditable(true);
		jPanel2.add(dbDriver);

		url.setEditable(true);
		jPanel2.add(url);

		jPanel2.add(user);

		jPanel2.add(password);

		jPanel6.add(jPanel2, java.awt.BorderLayout.CENTER);

		jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

		jPanel7.setLayout(new java.awt.BorderLayout());

		conectar.setText("Conectar");
		conectar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jPanel5.add(conectar);

		Jdbc2.setText("Jdbc2");
		jPanel5.add(Jdbc2);

		abrirTabela.setText("Abrir Tabela");
		abrirTabela.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jPanel5.add(abrirTabela);

		executarConsulta.setText("Executar Consulta");
		executarConsulta.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jPanel5.add(executarConsulta);

		jPanel7.add(jPanel5, java.awt.BorderLayout.NORTH);

		jPanel4.setLayout(new java.awt.GridLayout(3, 0));

		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Action(evt);
			}
		});
		jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				click(evt);
			}
		});

		jPanel4.add(jComboBox1);

		jLabel5.setText("Servidor:");
		jPanel4.add(jLabel5);

		jLabel6.setText("Ves\u00e3or:");
		jPanel4.add(jLabel6);

		jPanel7.add(jPanel4, java.awt.BorderLayout.CENTER);

		jPanel1.add(jPanel7, java.awt.BorderLayout.SOUTH);

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
		addInternalFrameListener(new InternalFrameAdapter() {
			public void internalFrameClosing(InternalFrameEvent e) {
				super.internalFrameClosing(e);
				BarraSetTop.removerJIntenalFrame(ConeccoesInternalFrame.this);
			}
		});
		pack();
	} // GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton3ActionPerformed

		// Add your handling code here:
		try {
			if (rs != null) {
				rs.close();
			}
			String tableName = (String) jComboBox1.getSelectedItem();
			PesquisaInternalFrame pesquisaInternalFrame = new PesquisaInternalFrame(
					null, tableName, stmt);
			MainFrame.jDesktopPane1.add(pesquisaInternalFrame);
			pesquisaInternalFrame.show();
			BarraSetTop.adicionarJIntenalFrame(pesquisaInternalFrame);
		} catch (Exception e) {
			JTextArea ta = new JTextArea(3, 15);
			ta.setText(e.toString());
			JOptionPane.showMessageDialog(this, ta, "Erro SQL",
					JOptionPane.ERROR_MESSAGE);
			e.printStackTrace();
		}
	} // GEN-LAST:event_jButton3ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton2ActionPerformed

		// Add your handling code here:
		try {
			String tableName = (String) jComboBox1.getSelectedItem();

			if (rs != null) {
				rs.close();
			}

			String query = "SELECT * FROM " + tableName;
			rs = stmt.executeQuery(query);

			PesquisaInternalFrame pesquisaInternalFrame;

			if (Jdbc2.isSelected()) {
				pesquisaInternalFrame = new PesquisaInternalFrame(
						new ScrollingResultSetTableModel(rs, true), tableName,
						stmt);
			} else {
				pesquisaInternalFrame = new PesquisaInternalFrame(
						new CachingResultSetTableModel(rs, true), tableName,
						stmt);
			}
			MainFrame.jDesktopPane1.add(pesquisaInternalFrame);
			pesquisaInternalFrame.show();
			BarraSetTop.adicionarJIntenalFrame(pesquisaInternalFrame);
			pesquisaInternalFrame.setMaximum(true);

		} catch (Exception e) {
			JTextArea ta = new JTextArea(3, 15);
			ta.setText(e.toString());
			JOptionPane.showMessageDialog(this, ta, "Erro SQL",
					JOptionPane.ERROR_MESSAGE);
			e.printStackTrace();
		}
	} // GEN-LAST:event_jButton2ActionPerformed

	private void click(java.awt.event.MouseEvent evt) { // GEN-FIRST:event_click

		// Add your handling code here:
	} // GEN-LAST:event_click

	private void Action(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_Action

		// Add your handling code here:
	} // GEN-LAST:event_Action

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_jButton1ActionPerformed

		// Add your handling code here:
		try {
			Class.forName((String) dbDriver.getSelectedItem());

			Connection con = DriverManager.getConnection((String) url
					.getSelectedItem(), user.getText(), new String(password
					.getPassword()));

			if (Jdbc2.isSelected()) {
				stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
						ResultSet.CONCUR_READ_ONLY);
			} else {
				stmt = con.createStatement();
			}

			DatabaseMetaData md = con.getMetaData();
			ResultSet mrs = md.getTables(null, null, null,
					new String[] { "TABLE" });

			while (mrs.next())
				jComboBox1.addItem(mrs.getString(3));

			mrs.close();
			jLabel5.setText("Servidor: " + md.getDatabaseProductName());
			jLabel6.setText("Versão: " + md.getDatabaseProductVersion());
		} catch (Exception e) {
			JTextArea ta = new JTextArea(3, 15);
			ta.setText(e.toString());
			JOptionPane.showMessageDialog(this, ta, "Erro SQL",
					JOptionPane.ERROR_MESSAGE);
			e.printStackTrace();
		}
	} // GEN-LAST:event_jButton1ActionPerformed
}
